config/routes.rb
Rails.application.routes.draw do

  root "cards#learn"
  
  resources :leitner_card_boxes
  resources :cards do
    collection do
      get :learn
      post :import
    end
    member do
      post :remember
      post :forget
    end
  end
  
  devise_for :users
  get 'memory_systems', to: 'memory_systems#index'
  get '/api/gpt/:message', to: 'api#gpt'
end

app/models/leitner_card_box.rb
class LeitnerCardBox < ApplicationRecord
  belongs_to :user
  has_many :cards

  validates :repeat_period, presence: true, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :user_id }

  # default repeat periods for new users
  DEFAULT_REPEAT_PERIODS = [1, 3, 7].freeze
  
  before_destroy :remove_associated_cards

  def next_box
    # You might want to limit the number of boxes.
    # Here it's assumed that the box with the higher repeat_period is the next box.
    user.leitner_card_boxes.where('repeat_period > ?', self.repeat_period).order(:repeat_period).first
  end

  # Class method to get the first box.
  def self.first_box(user)
    user.leitner_card_boxes.order(:repeat_period).first
  end

  def self.prev_box(user, current_box)
    # You might want to limit the number of boxes.
    # Here it's assumed that the box with the lower repeat_period is the previous box.
    user.leitner_card_boxes.where('repeat_period < ?', current_box.repeat_period).order(:repeat_period).last
  end

  private

  def remove_associated_cards
    cards.update_all(leitner_card_box_id: nil)
  end
end

app/controllers/leitner_card_boxes_controller.rb
class LeitnerCardBoxesController < ApplicationController
  before_action :set_leitner_card_box, only: %i[ show edit update destroy ]
  before_action :require_owner, only: %i[ show edit update destroy ]
  before_action :move_card_to_prev_box, only: %i[ destroy ]

  # GET /leitner_card_boxes or /leitner_card_boxes.json
  def index
    @leitner_card_boxes = current_user.leitner_card_boxes
  end

  # GET /leitner_card_boxes/1 or /leitner_card_boxes/1.json
  def show
  end

  # GET /leitner_card_boxes/new
  def new
    @leitner_card_box = LeitnerCardBox.new
  end

  # GET /leitner_card_boxes/1/edit
  def edit
  end

  # POST /leitner_card_boxes or /leitner_card_boxes.json
  def create
    @leitner_card_box = LeitnerCardBox.new(leitner_card_box_params)
    @leitner_card_box.user = current_user

    respond_to do |format|
      if @leitner_card_box.save
        format.html { redirect_to leitner_card_boxes_path, notice: "Leitner card box was successfully created." }
        format.json { render :show, status: :created, location: @leitner_card_box }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @leitner_card_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leitner_card_boxes/1 or /leitner_card_boxes/1.json
  def update
    respond_to do |format|
      if @leitner_card_box.update(leitner_card_box_params)
        format.html { redirect_to leitner_card_box_url(@leitner_card_box), notice: "Leitner card box was successfully updated." }
        format.json { render :show, status: :ok, location: @leitner_card_box }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @leitner_card_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leitner_card_boxes/1 or /leitner_card_boxes/1.json
  def destroy
    @leitner_card_box.destroy

    respond_to do |format|
      format.html { redirect_to leitner_card_boxes_url, notice: "Leitner card box was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leitner_card_box
      @leitner_card_box = LeitnerCardBox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def leitner_card_box_params
      params.require(:leitner_card_box).permit(:repeat_period, :user_id)
    end

    def require_owner
      unless current_user == @leitner_card_box.user
        redirect_to leitner_card_boxes_url, notice: "You are not authorized to do that."
      end
    end

    def move_card_to_prev_box
      # Move cards to the prev box before destroying the box.
      # This is done to prevent orphan cards.
      @leitner_card_box.cards.update_all(leitner_card_box_id: LeitnerCardBox.prev_box(current_user, @leitner_card_box).id)
    end
end

app/helpers/leitner_card_boxes_helper.rb
module LeitnerCardBoxesHelper
end

app/views/leitner_card_boxes/_form.html.erb
<%= form_with(model: leitner_card_box) do |form| %>
  <% if leitner_card_box.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(leitner_card_box.errors.count, "error") %> prohibited this leitner_card_box from being saved:</h2>

      <ul>
        <% leitner_card_box.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :repeat_period, style: "display: block" %>
    <%= form.number_field :repeat_period %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leitner_card_boxes/_leitner_card_box.html.erb
<div id="<%= dom_id leitner_card_box %>" class="card col-lg-3 mt-3">
  <div class="card-body">
    <h5 class="leitner-card-box__repeat_period">Repeat period:<%= leitner_card_box.repeat_period %></h5>
    <h6> Card boxes: <%= leitner_card_box.cards.count %></h6>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#card_box_collapse_<%= leitner_card_box.id %>" role="button" aria-expanded="false" aria-controls="card_box_collapse_<%= leitner_card_box.id %>">
      Show cards
    </a>
    <div class="collapse" id="card_box_collapse_<%= leitner_card_box.id %>">
      <ul>
        <% leitner_card_box.cards.each do |card| %>
          <li><%= card.word %></li>
        <% end %>
      </ul>
    </div>


    <%= link_to 'Edit', edit_leitner_card_box_path(leitner_card_box) %>
    <%= link_to 'Destroy', leitner_card_box, data: { confirm: 'Are you sure?' }, method: :delete %>
  </div>
</div>

app/views/leitner_card_boxes/edit.html.erb
<h1>Editing leitner card box</h1>

<%= render "form", leitner_card_box: @leitner_card_box %>

<br>

<div>
  <%= link_to "Show this leitner card box", @leitner_card_box %> |
  <%= link_to "Back to leitner card boxes", leitner_card_boxes_path %>
</div>

app/views/leitner_card_boxes/index.html.erb
<h1>Leitner card boxes</h1>

<div id="leitner_card_boxes" class="row">
  <% @leitner_card_boxes.order(:repeat_period).each do |leitner_card_box| %>
    <%= render leitner_card_box %>
  <% end %>
</div>

<%= link_to "New Leitner Card Box", new_leitner_card_box_path, class: "btn btn-dark mt-4" %>

app/views/leitner_card_boxes/new.html.erb
<h1>New leitner card box</h1>

<%= render "form", leitner_card_box: @leitner_card_box %>

<br>

<div>
  <%= link_to "Back to leitner card boxes", leitner_card_boxes_path %>
</div>

app/views/leitner_card_boxes/show.html.erb
<%= render @leitner_card_box %>

<%= link_to "Back to leitner card boxes", leitner_card_boxes_path %>