config/routes.rb
Rails.application.routes.draw do

  root "cards#learn"
  
  resources :leitner_card_boxes
  resources :cards do
    collection do
      get :learn
      post :import
    end
    member do
      post :remember
      post :forget
    end
  end
  
  devise_for :users
  get 'memory_systems', to: 'memory_systems#index'
  get '/api/gpt/:message', to: 'api#gpt'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :leitner_card_box

  def remember
    next_box = leitner_card_box.next_box
    
    if next_box
      # Move to the next box
      self.update(
        leitner_card_box: next_box,
        last_reviewed_at: Time.current
      )
    else
      # No next box, remove the card
      self.destroy
    end
  end

  def forget
    # Move back to the first box
    self.update(
      leitner_card_box: LeitnerCardBox.first_box(user),
      last_reviewed_at: Time.current
    )
  end
end

app/controllers/cards_controller.rb
require 'csv'

class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card, only: %i[ show edit update destroy ]
  before_action :require_owner, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = current_user.cards
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    @card.user = current_user
    @card.leitner_card_box = LeitnerCardBox.where(repeat_period: LeitnerCardBox.minimum(:repeat_period)).first
    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def learn
    current_date = Time.current
    @cards = current_user.cards.joins(:leitner_card_box)
                 .where("cards.last_reviewed_at IS NULL OR (EXTRACT(EPOCH FROM (? - cards.last_reviewed_at))/86400)::integer >= leitner_card_boxes.repeat_period", current_date)
    @card = @cards.sample
  end
  
  
  def remember
    @card = current_user.cards.find(params[:id])
    @card.remember
    redirect_to learn_cards_path
  end
  
  def forget
    @card = current_user.cards.find(params[:id])
    @card.forget
    # flash[:alert] = "#{@card.word}: #{ @card.definition }"
    redirect_to learn_cards_path
  end

  def import
    file = params[:file]
    if file.nil?
      flash[:error] = "You must select a file first"
    else
      new_cards_count = 0
      updated_cards_count = 0
      error_count = 0
  
      begin
        ActiveRecord::Base.transaction do
          CSV.foreach(file.path, headers: true) do |row|
            card = Card.find_or_initialize_by(
              word: row[2].strip, 
              user: current_user, 
              leitner_card_box: current_user.leitner_card_boxes.find_by(repeat_period: 1)
            )
            card.definition = row[3]
            if card.new_record?
              new_cards_count += 1 if card.save
            else
              updated_cards_count += 1 if card.save
            end
          rescue => e
            error_count += 1 # increment error count
            Rails.logger.error "Failed to import card: #{e.message}"
            next
          end
        end
  
        flash[:notice] = "Successfully imported #{new_cards_count} new cards and updated #{updated_cards_count} existing cards. Failed to import #{error_count} cards."
      rescue StandardError => e
        flash[:error] = "Error importing cards: #{e.message}"
      end
    end
    redirect_back(fallback_location: cards_path)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:word, :definition, :leitner_card_box_id)
    end

    def require_owner
      unless current_user == @card.user
        redirect_to cards_url, notice: "You are not authorized to perform this action."
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>" class="card col-12 col-md-3 mt-4 d m-auto" >
  <div class="card-body">
    <h5 class="card-word"><%= card.word %></h5>
    <p class="card-definition"><%= card.definition %></p>
    <p class="card-leitner-card-box-id"> Repeat period:  <%= pluralize(card.leitner_card_box.repeat_period,'day') %></p>
    <%= link_to 'Edit', edit_card_path(card), class: 'btn btn-outline-secondary' %>
    <%= link_to "Destroy Card", [card], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, class: 'btn btn-outline-danger' %>
  </div>
</div>

app/views/cards/_card_buttons.html.erb
<%= button_to "Edit", edit_card_path(card), method: :get, class: "btn btn-outline-dark ms-auto" %>
<button id='setting-word-btn' type="button" class="btn btn-outline-dark ms-2">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
  </svg>
</button>
<button onclick="speakText('<%= card.word %>')" id='listen-word-btn' type="button" class="btn btn-outline-dark ms-2">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-ear " viewBox="0 0 16 16">
    <path d="M8.5 1A4.5 4.5 0 0 0 4 5.5v7.047a2.453 2.453 0 0 0 4.75.861l.512-1.363a5.553 5.553 0 0 1 .816-1.46l2.008-2.581A4.34 4.34 0 0 0 8.66 1H8.5ZM3 5.5A5.5 5.5 0 0 1 8.5 0h.16a5.34 5.34 0 0 1 4.215 8.618l-2.008 2.581a4.555 4.555 0 0 0-.67 1.197l-.51 1.363A3.453 3.453 0 0 1 3 12.547V5.5ZM8.5 4A1.5 1.5 0 0 0 7 5.5v2.695c.112-.06.223-.123.332-.192.327-.208.577-.44.72-.727a.5.5 0 1 1 .895.448c-.256.513-.673.865-1.079 1.123A8.538 8.538 0 0 1 7 9.313V11.5a.5.5 0 0 1-1 0v-6a2.5 2.5 0 0 1 5 0V6a.5.5 0 0 1-1 0v-.5A1.5 1.5 0 0 0 8.5 4Z"></path>
  </svg>
</button>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, style: "display: block" %>
    <%= form.text_field :word %>
  </div>

  <div>
    <%= form.label :definition, style: "display: block" %>
    <%= form.text_area :definition %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/_media.html.erb
<% if !media.empty? %>
  <div class="d-flex flex-wrap">
    <% media.each do |url| %>
      <div class="col-12 col-md-6 col-lg-4">
        <img src='<%= url %>' loading="lazy" alt="media" class="img-fluid m-2" style="width: 100%; object-fit: cover;">
      </div>
    <% end %>
  </div>
<% else %>
  <p>No media found</p>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<h3>Import cards</h3>
<p> Import cards from a CSV file. The file must be an export file from Google translate </p>
<%= form_with url: import_cards_path, method: :post, local: true, multipart: true do |form| %>
  <div class="form-group input-group">
    <%= form.label :file, class: 'form-label' %>
    <%= file_field_tag :file, required: true, class: "form-control" %>
  </div>
  <%= form.submit "Import", class: "btn btn-primary mt-2" %>
<% end %>
<br/>
<%= link_to "Create new card", new_card_path, class: "btn btn-dark" %>
<h3>Cards</h3>
<div id="cards" class="row">
  <% @cards.each do |card| %>
    <%= render card %>
  <% end %>
</div>

<%= link_to "New card", new_card_path, class: "btn btn-dark mt-4" %>

app/views/cards/learn.html.erb
<% if @card %>
  <div class="card w-100">
    <div class="card-body">
      <div class="d-flex ms-auto">
        <%= render 'card_buttons', card: @card %>
      </div>
      <h6 class="card-subtitle mb-2 text-body-secondary"><%= @card.word %></h6>
      <div data-controller="gpt">
        <button class="btn btn-outline-dark" data-gpt-target="button" data-word='<%= @card.word %>' data-action="click->gpt#generate">Generate sentence</button>
        <div data-gpt-target="spinner" class="spinner-border text-light py-2" role="status" style="display: none;">
          <span class="visually-hidden">Loading...</span>
        </div>
        <span data-gpt-target="output" class="d-block pb-2"></span>
      </div>
      <div class="d-flex">
        <%= form_with(url: remember_card_path(@card), local: true) do %>
          <%= submit_tag "I remember", class: 'btn btn-success' %>
        <% end %>
      
        <%= form_with(url: forget_card_path(@card), local: true) do %>
          <%= submit_tag "I forgot", class: 'btn btn-danger mx-3' %>
        <% end %>
      </div>
      <div>
        <details>
          <summary>Definition</summary>
          <%= @card.definition %>
        </details>
      
        <details>
          <summary>Media</summary>
          <% media = MediaService.fetch_media(@card.word, 'gif') %>
          <%= render 'media', media: media %>
        </details>
      </div>
    </div>
  </div>

<% else %>
  <h1>No more cards to learn today</h1>
<% end %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<%= render @card %>