config/routes.rb
Rails.application.routes.draw do

  root "cards#learn"
  
  resources :leitner_card_boxes
  resources :cards do
    collection do
      get :learn
      post :import
    end
    member do
      post :remember
      post :forget
    end
  end
  
  devise_for :users
  get 'memory_systems', to: 'memory_systems#index'
  get '/api/gpt/:message', to: 'api#gpt'
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "alert" %>
    <div class="alert alert-warning alert-dismissible fade show"><%= message %></div>
  <% elsif message_type == "notice" %>
    <div class="alert alert-success alert-dismissible fade show"><%= message %></div>
  <% elsif message_type == "error" %> 
    <div class="alert alert-danger alert-dismissible fade show"><%= message %></div>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible fade show"><%= message %></div>
  <% end %>
  <script>
  $('document').ready(function() {
    setTimeout(function() {
      $('.alert').slideUp();
    }, 3000);
  });
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center p-3 border-top">
  <p class="col-md-4 mb-0 text-body-secondary">© 2023 Company, Inc</p>

  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
  </a>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "MemorizeApp", root_path, class: 'navbar-brand text-dark' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
      </svg>
    </button>
    <div class="navbar-collapse collapse" id="navbarTogglerDemo02" style="">
      <ul class="d-flex w-100 navbar-nav me-auto py-2 mb-lg-0">
        <% if current_user %>
          <%= link_to "Learn", learn_cards_path, class: 'nav-link' %>
          <%= link_to "Cards", cards_path, class: 'nav-link' %>
          <%= link_to "Card boxes", leitner_card_boxes_path, class: 'nav-link' %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn bg-gradient-primary mb-0 ms-auto" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn bg-gradient-primary m-1" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn bg-gradient-primary m-1" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemorizeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/material-kit/3.0.3/css/material-kit.min.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id="main-wrap" class="container pt-4">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  
  </body>
</html>